services:

  # PHP webpage service
  web:
    build:
      context: php-web
      target: builder # Builds using the Dockerfile in php-web
    ports:
      - '80:80'
    volumes:
      - ./php-web:/var/www/html
    depends_on:
      - db

  # MySQL database
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_admin
      MYSQL_PASSWORD: password # Should be in env var
      MYSQL_ROOT_PASSWORD: 12345 
    volumes:
      - './mysql:/docker-entrypoint-initdb.d' # sync persistent initial SQL file

  # PHP MyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8001:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db